name: Build Android DEBUG

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions: { contents: read }

concurrency:
  group: android-debug-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-debug:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Install deps
        run: npm ci
      - name: Build web (Vite)
        run: npm run build

      - name: Show build output
        run: |
          ls -la dist || true
          echo "Capacitor Android files:"
          ls -la node_modules/@capacitor/android/ || true

      - name: Capacitor copy+sync
        run: npm run cap:sync
      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '17' }
      - name: Build DEBUG APK
        working-directory: android
        timeout-minutes: 10
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug --stacktrace --info
      - name: Upload APK (debug)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/*.apk
