name: Build Android DEBUG

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions: { contents: read }

concurrency:
  group: android-debug-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-debug:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Install deps
        run: npm ci
      - name: Build web (Vite)
        run: npm run build

      - name: Show build output
        run: |
          ls -la dist || true
          echo "Capacitor Android files:"
          ls -la node_modules/@capacitor/android/ || true

      - name: Capacitor copy+sync
        run: npm run cap:sync
      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '17' }
      - name: Build DEBUG APK
        working-directory: android
        timeout-minutes: 10
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug --stacktrace --info 2>&1 | tee build.log
          echo "=== BUILD LOG END ==="
          if [ $? -ne 0 ]; then
            echo "=== LAST 50 LINES OF BUILD LOG ==="
            tail -50 build.log
            echo "=== COMPILATION ERRORS ==="
            grep -A 5 -B 5 "error:" build.log || echo "No specific errors found"
            exit 1
          fi
      - name: Check APK output directory
        working-directory: android
        run: |
          echo "=== APK BUILD VERIFICATION ==="
          find . -name "*.apk" -type f | head -10
          ls -la app/build/outputs/apk/ || echo "No apk directory found"
          ls -la app/build/outputs/apk/debug/ || echo "No debug directory found"
          
      - name: Upload APK (debug)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/**/*.apk
          if-no-files-found: warn
