name: Build Android DEBUG

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Install deps & build web
        run: |
          npm ci
          npm run build || npm run build:web || echo "no web build step"

      - name: Capacitor sync (if present)
        run: |
          npx cap sync android || echo "no Capacitor, continuing"

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK (cmdline-tools)
        uses: android-actions/setup-android@v3
        # ne passe PAS 'packages' ici : on installe à la main juste après

      - name: Install Android SDK packages (with retry + fallback)
        shell: bash
        run: |
          set -euxo pipefail
          export ANDROID_SDK_ROOT="${ANDROID_HOME:-$ANDROID_SDK_ROOT}"
          export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"

          # S'assurer que cmdline-tools existent (certains runners les mettent ailleurs)
          if ! command -v sdkmanager >/dev/null 2>&1; then
            echo "sdkmanager not found"; ls -la "$ANDROID_SDK_ROOT"; exit 1
          fi

          yes | sdkmanager --licenses

          install_pkg () {
            local PKG="$1"
            sdkmanager "$PKG" || sdkmanager --channel=0 "$PKG"
          }

          # Paquets cibles
          install_pkg "platform-tools"
          install_pkg "build-tools;34.0.0" || install_pkg "build-tools;33.0.2"
          install_pkg "platforms;android-34" || install_pkg "platforms;android-33"

          echo "Installed packages:"
          sdkmanager --list || true

      - name: Build DEBUG APK
        working-directory: android
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Upload APK (debug)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/*.apk
